"""honeypot

Revision ID: 58069f19df5f
Revises: 43c939c3d630
Create Date: 2023-06-11 19:50:55.555426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58069f19df5f'
down_revision = '43c939c3d630'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('honeypot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(length=50), nullable=False),
    sa.Column('user_agent', sa.String(length=250), nullable=False),
    sa.Column('headers', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('honeypot')
    # ### end Alembic commands ###
